### ISSUE TITLE
Are the variable values going to be the same or different between environments?

### ISSUE THREAD

**Issue by anderskitson** [CMeeg/next-azure#11]
I have read you article on deploying Next JS with Azure Pipelines

I was wondering about this specific line 

Are the variable values going to be the same or different between environments?

If the case is the variables values are different. Does that mean they have to be accessed at run time?

Since the build would be atomic across the entire release stages. How would we access the env variables such as a new Apollo client call to different graphQL instances per environment. Is this the only way because I don't want to lost static generation on the app.

```
return new ApolloClient({
    name: 'client',
    ssrMode: typeof window === 'undefined',
    link: createHttpLink({
      uri: ()=> getConfig().publicRuntimeConfig.GRAPHQL_URL,
      credentials: 'same-origin',
      headers: httpLinkHeaders
    }),
    cache: new InMemoryCache()
  });
```

**Comment by CMeeg** [comment]
The variable values can be different between environments. You can choose to create variables individually for each environment, or set a "default" value and "overwrite" it for specific environment(s). There is some detail in the docs about [adding additional app settings](next-kontent-template), which are exposed as [environment variables](https://nextjs.org/docs/basic-features/environment-variables) in the Next app.

If you're using the pipeline from this repo then the variables from the variable groups are also available in the pipeline as environment variables so they will be used during static generation when `next build` is run in the pipeline.

Each run of the pipeline deploys to only one environment, and only the variables relevant to that environment are used in the pipeline and deployed as app settings to the app service / app service slot with the app so that they can be used as environment variables by Next features like Incremental Static Regeneration, API routes etc.

So the build is not atomic across the entire release stages, each build goes to a single environment only. I couldn't think of a way around this due to the nature of static generation, and I wanted to stay away from [runtime configuration](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration) as it's not preferred.

I'd like to be able to do one build and deploy the same build artifacts to multiple environments so if you have any thoughts or suggestions around that it'd be great to hear them.
