### ISSUE TITLE
Discouraged use of pm2 in a Dockerfile

### ISSUE THREAD

**Issue by advename** [CMeeg/next-azure#14]
I've read through your post [Using Docker Compose to deploy to a Next.js app to a Linux App Service in Azure](https://meeg.dev/blog/using-docker-compose-to-deploy-to-a-next-js-app-to-a-linux-app-service-in-azure) to find inspiration for my architecture and noticed you're using pm2 instead of npm to run the server.

I was curious to why, since IIRC pm2 restarts the server upon server error, a feature that docker already does on its own. Upon further [research](https://stackoverflow.com/a/55245460), I found out that even [Docker themselves discourage the usage of pm2](https://www.docker.com/blog/keep-nodejs-rockin-in-docker/).

I would therefore advise reconsidering using pm2 in this repo and in your blog post :)

I'll raise this issue with [Steve Holgado's post](https://steveholgado.com/nginx-for-nextjs/#pm2) as well, from which I believe you got the inspiration from.

**Comment by CMeeg** [comment]
Thanks for raising this - I wasn't sure if pm2 was needed or not tbh... as I put in the blog post:

_"I found conflicting guidance on whether pm2 is useful inside a Docker container (so weird not to find consensus on the internet, right?!) - Next don't use it (or anything similar) in their sample, but it was recommended in Steve Holgado's article, and I know Microsoft use it in a lot of their sample apps so I ended up adding it as it sounded like a "good to have" on balance"_

Ultimately the reason I kept it in there was not being able to find definitive information from Microsoft as to how App Service monitors containers and what it will do if one of the containers in a multi-container deployment goes down. I saw a bunch of posts like the one you have cited on Stack Overflow etc, but because there was nothing definitive (just conflicting opinions) I thought having pm2 in there was better than not having it in there. It's easy enough for people to pull it out if they don't want it.

My expectation is that it should be the job of some higher level component to monitor containers and restart if necessary, not the container itself so I agree with you that it _shouldn't_ be needed - and that's what that Docker article you've linked to is getting at. That higher level component could be Kubernetes in which case I'm sure it takes care of this and does make pm2 redundant, but in this case that higher level component is App Service and I just don't know with any certainty what it would do in this scenario.

I should reach out to Microsoft for clarification and then I can update the blog post and sample app once I get something definitive on this!

**Comment by advename** [comment]
> That higher level component could be Kubernetes in which case I'm sure it takes care of this and does make pm2 redundant, but in this case that higher level component is App Service and I just don't know with any certainty what it would do in this scenario.

Oh - this makes a lot of sense. Haven't thought that far that Microsoft might handle restarts differently.

AFAIK, App Service seems to restart containers during start up. They do that by making a request to the container, and if that returns a 5XX, then the container is restarted. ([How does the container warmup request work?](https://learn.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#how-does-the-container-warmup-request-work-)). However, I don't know if there's anything for runtime.

Would love to hear feedback if you've reached out to Microsoft :)

**Comment by CMeeg** [comment]
I have created a new template for getting Next.js into Azure so I am archiving this repo and in the process closing this issue.

If you're insterested the new template is [nextjs-aca](https://github.com/CMeeg/nextjs-aca) and it doesn't use pm2.
