### ISSUE TITLE
Installing dependencies after deployment

### ISSUE THREAD

**Issue by AidanRRR** [CMeeg/next-azure#3]
Thanks for sharing your setup!

If I'm not mistaken, you actually do the following:
- Build, package it (including node modules).
- Deploy to your resource.
- Run an additional npm install on the actual app service to link native dependencies.

Is this correct? I'm struggling a bit with the last step.

The reason why I'm asking is to gain a bit more knowledge in this step. I've got a similar setup on which I just only do a release:
- Download latest version from git and deploy

Then post deployment script:
- Install required dependencies
- Build app

This seems to work; but the kudu part with the post deployment I don't fully understand. This seems to run in a nodejs version 10. And it does not seem possible to change this. Did you do that in the deploy file you have?

**Comment by CMeeg** [comment]
No worries - hopefully it's been helpful!

The steps in the pipeline boil down to:

* Create / update the resources (app service, CDN etc)
* Build and package the app (not including node_modules) into a `dist` folder
  * This step places [all the Next build outputs, plus some additional files](https://github.com/CMeeg/next-azure/blob/main/.azure/azure-pipelines.yml#L97-L116) required by the app service to run a node app into a `dist` folder
* Deploy the `dist` folder to the app service via web deploy

Then when the app service receives the deployment it will run a Kudu custom deployment script that is primarily there to [run yarn install](https://github.com/CMeeg/next-azure/blob/main/.azure/web-app/deploy.cmd#L108) - this deployment script is deployed to the app service with everything else in the `dist` folder.

I would have liked to push up `node_modules` with the deployment given I have already done that in the pipeline, but if I do that the web deploy step in the pipeline takes sometimes upwards of 30 mins! Not deploying `node_modules` and running `yarn install` on the app service is more like 1 to 5 mins depending on volume of changes.

It sounds like you have a pretty similar approach, except you are doing the build on the app service via Kudu also. The post-deployment script is a little hard to understand, I agree, especially as it's a `.cmd` script and I don't have a lot of experience with those. I found some [documentation](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script) that helped me with it as well as [another repo](https://github.com/stefangordon/kudu-yarn) on GitHub as an example that helped me as I was using Yarn and the default scripts were using npm.

As for the Node version - check if you have the `WEBSITE_NODE_DEFAULT_VERSION` application setting set to `12.13.0`. With that in place if I run `node -v` from the Kudu console it returns `v12.21.0`. I must have read about that setting somewhere, but I can't find any "official" documentation for it just doing a quick search now so I'm not sure what other valid versions are available, but Node 12 is enough to satisfy Next (for now)!

![image](https://user-images.githubusercontent.com/940607/135350208-8d9a0032-f4ff-4538-a742-c39f498fee8c.png)

If you haven't come across my blog posts I wrote out my approach for Next on Azure [here](https://meeg.dev/blog/using-azure-pipelines-to-build-and-deploy-a-next-js-app-to-azure-app-services) and [here](https://meeg.dev/blog/automating-azure-infrastructure-deployments-using-bicep-and-azure-pipelines), which may also help to have a scan through for ideas. I've been tinkering with the approach a bit since I wrote those posts so the repo is more up to date, but they might still be of some use. 

Hope that helps!

**Comment by AidanRRR** [comment]
Thanks for the elaborate reply!
Only with `WEBSITE_NODE_DEFAULT_VERSION` I could still not get a specific version in kudu.

After retrying I ended up doing deployment by shipping the whole node_modules folders in a zip. You say it took up to 30 minutes at your end?

I'm not sure, maybe my setup / project is a bit different, but perhaps this speed can be improved by using a more recent version of node & npm (using node: 14 at the moment and npm: 7).

The build pipeline seems to take about 2-4 minutes (usually around 2) and the release itself usually 4 minutes up to (not often 8 minutes). Task name: 'Package deployment using ZIP Deploy'. Again, perhaps the projects are different; but I did got it to work a lot faster with more a recent version of node and npm.

Again, thanks for going into detail and thanks for writing the blog post! Dedefinitely gave me more knowledge about how this works.
